// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wire

import (
	"github.com/laidingqing/stackbuild/cmd/runner/application"
	"github.com/laidingqing/stackbuild/cmd/runner/config"
)

// Injectors from wire.go:

func InitializeApplication(config2 config.Config) (application.Application, error) {
	grpcServer := provideServer(config2)
	applicationApplication := application.NewApplication(grpcServer)
	return applicationApplication, nil
}
