// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wire

import (
	"github.com/laidingqing/stackbuild/cmd/server/application"
	"github.com/laidingqing/stackbuild/cmd/server/config"
	"github.com/laidingqing/stackbuild/handler/api"
	"github.com/laidingqing/stackbuild/handler/web"
)

// Injectors from wire.go:

func InitializeApplication(config2 config.Config) (application.Application, error) {
	server := api.New()
	webServer := web.New()
	mux := provideRouter(server, webServer)
	serverServer := provideServer(mux, config2)
	sessionStore, err := provideDatabase(config2)
	if err != nil {
		return application.Application{}, err
	}
	userStore := provideUserStore(sessionStore)
	applicationApplication := application.NewApplication(serverServer, userStore)
	return applicationApplication, nil
}
