#!/bin/sh

if [[ ! -z "${STACK_BUILD_WORKSPACE}" ]]; then
	cd ${STACK_BUILD_WORKSPACE}
fi

if [[ ! -z "${STACK_BUILD_NETRC_MACHINE}" ]]; then
	cat <<EOF > /root/.netrc
machine ${STACK_BUILD_NETRC_MACHINE}
login ${STACK_BUILD_NETRC_USERNAME}
password ${STACK_BUILD_NETRC_PASSWORD}
EOF
fi

if [[ ! -z "${SSH_KEY}" ]]; then
	mkdir /root/.ssh
	echo -n "$SSH_KEY" > /root/.ssh/id_rsa
	chmod 600 /root/.ssh/id_rsa

	touch /root/.ssh/known_hosts
	chmod 600 /root/.ssh/known_hosts
	ssh-keyscan -H ${STACK_BUILD_NETRC_MACHINE} > /etc/ssh/ssh_known_hosts 2> /dev/null
fi

# configure git global behavior and parameters via the
# following environment variables:


if [[ -z "${STACK_BUILD_COMMIT_AUTHOR_NAME}" ]]; then
	export STACK_BUILD_COMMIT_AUTHOR_NAME=stackbuild
fi

if [[ -z "${STACK_BUILD_COMMIT_AUTHOR_EMAIL}" ]]; then
	export STACK_BUILD_COMMIT_AUTHOR_EMAIL=stackbuild@localhost
fi

export GIT_AUTHOR_NAME=${STACK_BUILD_COMMIT_AUTHOR_NAME}
export GIT_AUTHOR_EMAIL=${STACK_BUILD_COMMIT_AUTHOR_EMAIL}
export GIT_COMMITTER_NAME=${STACK_BUILD_COMMIT_AUTHOR_NAME}
export GIT_COMMITTER_EMAIL=${STACK_BUILD_COMMIT_AUTHOR_EMAIL}

CLONE_TYPE=$STACK_BUILD_BUILD_EVENT
case $STACK_BUILD_COMMIT_REF in
  refs/tags/* ) CLONE_TYPE=tag ;;
esac

case $CLONE_TYPE in
pull_request)
	clone-pull-request
	;;
tag)
	clone-tag
	;;
*)
	clone-commit
	;;
esac