#!/bin/sh

FLAGS=""
if [[ ! -z "${PLUGIN_DEPTH}" ]]; then
	FLAGS="--depth=${PLUGIN_DEPTH}"
fi

if [ ! -d .git ]; then
	git init
	git remote add origin ${STACK_BUILD_REMOTE_URL}
fi

set -e
set -x

git fetch ${FLAGS} origin +refs/heads/${STACK_BUILD_COMMIT_BRANCH}:
git checkout ${STACK_BUILD_COMMIT_BRANCH}

git fetch origin ${STACK_BUILD_COMMIT_REF}:
git merge ${STACK_BUILD_COMMIT_SHA}