// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/laidingqing/stackbuild/cmd/server/config"
	"github.com/laidingqing/stackbuild/handler/api"
	"github.com/laidingqing/stackbuild/handler/web"
)

// Injectors from wire.go:

func InitializeApplication(config2 config.Config) (application, error) {
	server := api.New()
	webServer := web.New()
	mux := provideRouter(server, webServer)
	serverServer := provideServer(mux, config2)
	mainApplication := newApplication(serverServer)
	return mainApplication, nil
}
